## GENERAL ##
alias mkdir='mkdir -pv'
alias e='nano'
alias E='sudo nano'
alias nano='nano -lmEWexD_! -T 2'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -F'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -v'
alias ls='ls --color=auto'
alias ln='ln -v'
alias grep='grep'
alias diff='diff'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias back='cd $OLDPWD'
alias c='clear'
alias cd..='cd ..'
alias j='jobs -l'
alias h='history'
alias install='sudo apk add'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## CUSTOM ##
alias fuck='echo -e "~ okay dumbass\n~ sudo $(history -p !!)\n";sudo $(history -p !!) '
alias gauth='genauth'
alias genauth='echo "user: $(tr -dc 'a-zA-Z' < /dev/urandom | dd bs=4 count=2 2>/dev/null)"; echo "p_16: $(tr -dc "\&\_a-zA-Z0-9\^\*\@" < /dev/urandom | dd bs=4 count=4 2>/dev/null)"; echo "p_24: $(tr -dc "\&\_a-zA-Z0-9\^\*\@" < /dev/urandom | dd bs=4 count=6 2>/dev/null)"'
alias nsh='newscript'
alias newscript='echo -e "#!/usr/bin/env bash\n#set -Eeuxo pipefail\nset -e" | nano -'

## PROGRAM SPECIFIC ##
alias d='docker'
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dlog='docker logs -f'
alias dit='docker exec -it'
alias chalias='ealias'
alias ealias='nano ~/.bash_aliases'
alias realias='source ~/.bash_aliases'
